const CracoLessPlugin = require('craco-less');

module.exports = {
  plugins: [
    {
      plugin: CracoLessPlugin,
      options: {
        lessLoaderOptions: {
          lessOptions: {
            modifyVars: { 
              '@primary-color': '#6198f3',
              '@success-color': '#65cd94',
              '@info-color': '@primary-color',
              '@warning-color': '#e9ac45',
              '@error-color': '#df4039',
              '@highlight-color': '#ce464d',
              '@processing-color': '@primary-color',
              '@body-background': '#f5f6fb',
              '@text-color': 'rgba(26, 27, 31, 1)',
              '@text-color-secondary': 'fade(@text-color, 45%)',
              '@border-color-base': '#dedede',
              '@border-color-split': '#dedede',
              '@layout-body-background': '#f5f6fb',
              '@font-size-base': '12px',
              '@border-radius-base': '5px',
              '@border-radius-sm': '5px',
              '@outline-width': '0',
              '@outline-color': '#737373',
              '@background-color-base': 'hsv(0, 0, 96%)',
              '@btn-default-bg': '#fafafa',
              '@btn-default-border': '#dedede',
              '@radio-button-bg': 'transparent',
              '@radio-button-checked-bg': 'transparent',
              '@form-item-margin-bottom': '16px',
              '@input-height-lg': '36px',
              '@input-hover-border-color': '#737373',
              '@progress-radius': '0',
              '@table-header-bg': '@layout-body-background',
              '@table-header-color': '#969aa7',
              '@table-row-hover-bg': '#fafafa',
              '@table-padding-vertical': '15px',
              '@tabs-card-gutter': '-1px',
              '@tabs-card-tab-active-border-top': '2px solid @primary-color',
              '@switch-color': '@success-color',
              '@breadcrumb-base-color': '@text-color',
              '@breadcrumb-last-item-color': '@text-color-secondary',
              '@slider-handle-border-width': '1px',
              '@slider-handle-shadow': '1px 1px 4px 0 rgba(0,0,0,.13)',
              '@slider-track-background-color': '@primary-color',
              '@slider-track-background-color-hover': '@primary-color',
              '@slider-handle-color': '#dedede',
              '@slider-handle-color-hover': '#dedede',
              '@slider-handle-color-focus': '#dedede',
              '@slider-handle-color-focus-shadow': 'transparent',
              '@slider-handle-color-tooltip-open': '#ddd',
              '@alert-success-border-color': '#dff4e5',
              '@alert-success-bg-color': '#dff4e5',
              '@alert-info-border-color': '#e5f3ff',
              '@alert-info-bg-color': '#e5f3ff',
              '@alert-warning-border-color': '#fff7db',
              '@alert-warning-bg-color': '#fff7db',
              '@alert-error-border-color': '#fcebea',
              '@alert-error-bg-color': '#fcebea',
            },
            javascriptEnabled: true,
          },
        },
      },
    },
  ],
};